### ISSUE TITLE
Performance on Cityscapes

### ISSUE THREAD

**Issue by qqwwee1231** [juntang-zhuang/ShelfNet-lw-cityscapes#2]
Thanks for releasing the code!  
May I know which resolution is used to achieve 74.8 mIoU on Cityscapes?

**Comment by juntang-zhuang** [comment]
It's 1024x2048, same size as the original input images.

**Comment by feinanshan** [comment]
I tested with "test_speed.py" at that resolution but got only about 45 fps. Maybe something wrong with this code?

**Comment by qqwwee1231** [comment]
I tested with "test_speed.py" at this resolution, but got only about 45fps. Maybe something run?
